name: ascii artwork
on: push

jobs:
    ascii_artwork_job:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            
            - name: checkout repo files
              run: ls -la

            - name: execute ascii-script
              run: ./ascii-script.sh