name: my first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            
            - name: welcome message and list files and show current directory and read file content
              run: |
                echo "Welcome to my first workflow"
                ls -la
                pwd
                cat README.md
            
                


            # - name: list files
            #   run: ls -
                
            # - name: show current directory
            #   run: pwd

            # - name: read file content
            #   run: cat README.md
